train:
  epochs: 1
  batch_size: 64
  eval_batch_size: 64
  warmup_ratio: 0.1
  lr: 2e-5
  weight_decay: 1.0e-4
  eval_steps: 500
  save_steps: 1000

dataset:
  datalist: ["chexpert-train", "mimic-cxr-train"]
  img_size: 224
  mean: 0.5862785803043838
  std: 0.27950088968644304