dataset:
  img_size: 224
  dataset_dir: /Users/sandradening/Desktop/SU/Coding/vlm-seminar/annotations/rsna/
  train_csv: /Users/sandradening/Desktop/SU/Coding/vlm-seminar/annotations/rsna/train.csv
  valid_csv: /Users/sandradening/Desktop/SU/Coding/vlm-seminar/annotations/rsna/val.csv
  test_csv: /Users/sandradening/Desktop/SU/Coding/vlm-seminar/annotations/rsna/test.csv
  
cls:
  img_size: 224
  # backbone: resnet_50 #resnet and vit are supported
  backbone: vit_base
  multilabel: False
  embed_dim: 128  
  # in_features: 2048 #resnet
  in_features: 768 #vit
  num_classes: 2
  pretrained: True #False will use the image net pretrained weights
  freeze: False
  # checkpoint: /u/home/galc/VLP-Seminar/pretrained/convirt-vit/epoch=17-step=31949.ckpt # CONVIRT
  checkpoint: /Users/sandradening/Desktop/SU/Coding/vlm-seminar/pretrained/pytorch_model.bin # MEDCLIP
  lr: 1.0e-4
  dropout: 0.0 #0.2
  weight_decay: 1.0e-6
  hidden_dim: 1024 #for medclip
  #finetuned_checkpoint: /u/home/galc/VLP-Seminar/data/ckpts/FinetuneCLS/rsna/2025_01_17_17_58_24/epoch=12-step=3782.ckpt # CONVIRT
  finetuned_checkpoint: /u/home/galc/VLP-Seminar/data/ckpts/FinetuneCLS/rsna/2025_01_19_13_03_24/epoch=37-step=11057.ckpt # MEDCLIP



det:
    img_size: 224
    backbone: resnet_50 #only resnet_50 is supported
    lr: 5.0e-4
    weight_decay: 1.0e-6
    conf_thres: 0.5
    iou_thres: [0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75]
    nms_thres: 0.5
    pretrained: True
    freeze: True
    max_objects: 10
    # checkpoint: /home/june/Code/MGCA-main/data/ckpts/resnet_50.ckpt
    checkpoint: /u/home/galc/mgca-modified/data/ckpts/ConVIRT/2024_12_25_14_19_23/epoch=17-step=31949.ckpt

